/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author M SURYA PANDI
 */
public class adimitPatient extends javax.swing.JFrame implements Runnable  {
     int hour,minutes,seconds;
    /**
     * Creates new form adimitPatient
     */
    public adimitPatient() {
        initComponents();
        showDate();
        Thread t = new Thread(this);
        t.start();
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("dd-MM-yyyy");
        pad.setText(sd.format(d));
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pid = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pn = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        pd = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        pcd = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        pad = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        pat = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        pbn = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 370, -1));

        pid.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pid.setForeground(new java.awt.Color(250, 0, 0));
        pid.setOpaque(false);
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 250, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 212, 370, 10));

        pn.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pn.setForeground(new java.awt.Color(250, 0, 0));
        pn.setOpaque(false);
        getContentPane().add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 250, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 282, 370, 10));

        pd.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pd.setForeground(new java.awt.Color(250, 0, 0));
        pd.setOpaque(false);
        getContentPane().add(pd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 250, 30));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 352, 370, 10));

        pcd.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pcd.setForeground(new java.awt.Color(250, 0, 0));
        pcd.setOpaque(false);
        getContentPane().add(pcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 250, 30));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 412, 370, 20));

        pad.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pad.setForeground(new java.awt.Color(250, 0, 0));
        pad.setOpaque(false);
        pad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padActionPerformed(evt);
            }
        });
        getContentPane().add(pad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 250, 30));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 472, 370, 10));

        pat.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pat.setForeground(new java.awt.Color(250, 0, 0));
        pat.setOpaque(false);
        getContentPane().add(pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 250, 30));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 370, -1));

        pbn.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        pbn.setForeground(new java.awt.Color(250, 0, 0));
        pbn.setOpaque(false);
        pbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbnActionPerformed(evt);
            }
        });
        getContentPane().add(pbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 270, 30));

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jButton3.setText("LogOut");
        jButton3.setOpaque(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, 150, 50));

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jButton2.setText("Back");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 150, 50));

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jButton1.setText("Admit Patient");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 270, 70));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Admit Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 220, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Admit Time:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, 40));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Consulted Doctor:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 240, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Disease:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 160, 40));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Alloted Bed Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 280, 40));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Patient Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Patient Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, 40));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIT PATIENTS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalsystem/doctor-stethoscope-hand-hospital-background-gown-94227568.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1050, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void padActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_padActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void pbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/new hospital", "root", "");
            Statement st = (Statement)conn.createStatement();
            String sql = "insert into patient_record values (?,?,?,?,?,?,?)";
            PreparedStatement ptst = conn.prepareStatement(sql);
            ptst.setString(1, pid.getText());
            ptst.setString(2, pn.getText());
            ptst.setString(3, pd.getText());
            ptst.setString(4, pcd.getText());
            ptst.setString(5, pad.getText());
            ptst.setString(6, pat.getText());
            ptst.setString(7, pbn.getText());  
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATA INSERTED SUCCEFULLY");
            conn.close();
            pid.setText("");pn.setText("");
            pd.setText("");
            pcd.setText("");
            pad.setText("");
            pat.setText("");
            pbn.setText("");

            
            //ResultSet rs = ptst.executeQuery();
                     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adimitPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adimitPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adimitPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adimitPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adimitPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField pad;
    private javax.swing.JTextField pat;
    private javax.swing.JTextField pbn;
    private javax.swing.JTextField pcd;
    private javax.swing.JTextField pd;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pn;
    // End of variables declaration//GEN-END:variables
  
 

    @Override
    public void run() {
       while(true){
           Calendar cal = Calendar.getInstance();
           hour=cal.get(Calendar.HOUR_OF_DAY);
           minutes=cal.get(Calendar.MINUTE);
           seconds=cal.get(Calendar.SECOND);
           
           SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm:ss aa");
           Date dat = cal.getTime();
           String time24= sdf24.format(dat);
           pat.setText(time24);
           
           
           
       }
    }



}
